### ISSUE TITLE
Color legend not showing

### ISSUE THREAD

**Issue by juferban** [Alanocallaghan/d3heatmap#2]
Hi Alan,

I am trying to generate the heatmap with the color legend and as mentioned I have a issue with the color legend not showing.
After some research I found that part of the legend is being displayed on the top-left corner but the size is so small that I can only see a letter from the legend title.

Looking into the generated code I noticed that all the width and height of the "class=bar" elements is set to 0. Same for the Y values.

On the console log I got the following error:
d3heatmap.js:48 
Uncaught TypeError: self.getId is not a function(anonymous function) @ d3heatmap.js:48
img.onload @ d3heatmap.js:98

Here is a simple code I used for the test:
library(shiny)
library(d3heatmap)

#Create a data matrix
x <- matrix( c(2, 4, 3, 8,5 ,9 ,3 ,5 ,7 ,9 ,7 ,5 ,3 ,6 ,7 , 1, 5, 7, 6, 1),
             nrow=4, ncol=5)

#UI with title and heatmap
ui <- fluidPage(
  titlePanel("d3heatmap example"),
  
  d3heatmapOutput("multiHeatmap", height = "800px") 
)

#Call to server to generate the heatmap with color legend enabled.
server <- function(input, output) {
  output$multiHeatmap <- renderD3heatmap({
    d3heatmap(x, 
              main = "TEST",
              show_color_legend = TRUE,
              scale = "column"
    )
  })
}
shinyApp(ui = ui, server = server)

![heatmap_test](https://cloud.githubusercontent.com/assets/5916739/17873890/fef497f2-687c-11e6-842e-049c40eee43c.png)

**Comment by Alanocallaghan** [comment]
I'll look into this this evening, I didn't test it using Shiny so this may be the fault of my CSS. Thanks for the detailed debug!

**Comment by Alanocallaghan** [comment]
Hi that should be fixed now, sorry for the delay. Obviously let me know if it persists (I still need to find a more sensible solution to be honest). 

I hadn't tested recently using Shiny so thanks for the issue and don't hesitate to log any more if you see any! Cheers

**Comment by juferban** [comment]
Hi Alan,

Thanks a lot. I updated the library to the latest version and run my test script and work perfect right now.
I will try to integrate it into my more complex tool and will let you know if I find any other issues.

Thanks a lot for taking the time to implement this feature and for fixing this bug so quickly. Really appreciated.

Julio

**Comment by Alanocallaghan** [comment]
Cheers Julio best of luck!
