### ISSUE TITLE
xaxis.style not a function error when running in Shiny app.

### ISSUE THREAD

**Issue by juferban** [Alanocallaghan/d3heatmap#5]
Hi Alan,

All of a sudden my heatmap have stop working when using them in Shiny.
The error I got when inspecting the console is 

> xaxis.style is not a function at heatmapcore.js line 276

The same code seem to work fine is I just run it outside of shiny in R-studio.

It may be that something in D3 have changed that is breaking the code?
I will investigate the issue but not very familiar with D3 and javascript so may take a while but was wondering if you have noticed a similar issue.

I will let you know of any findings.

Thanks,

Julio

**Comment by juferban** [comment]
I was not able to reproduce the error outside of my application when running it on the server so it may be some issue with the versions of the libraries and not related to the d3heatmap code.

I'll close the issue but will let you know if I find anything that may need your attention.

Cheers,

Julio

**Comment by Alanocallaghan** [comment]
I'll have a look into this at the weekend and see if I can reproduce it. I pushed some relatively major edits recently so may have messed something up...

**Comment by juferban** [comment]
Hi Alan,

Thanks a lot for your answer. I did some tests using a minimal example both in "plain" R and as a shiny app and was not able to reproduce the error. Even more, If I manually run each step of my app I can get the heatmap with no problem. It seems like the error is only where I try to run my app. I am trying to clean up my code and simplify it case there is some hidden bug from my side that is causing the issue.

Thanks again.

Julio

**Comment by Alanocallaghan** [comment]
Okay good news! There can be a lot of variables to work with when it comes to javascript. If you encounter it again just post the code here and I'll get cracking.
